import { NextResponse } from "next/server";
import * as pdfParseModule from "pdf-parse";
// @ts-ignore
const pdfParse = typeof pdfParseModule.default === 'function' ? pdfParseModule.default : pdfParseModule;

// Hardcoded keywords to match against the resume
const TARGET_KEYWORDS = [
  "javascript", "typescript", "react", "nextjs", "node.js", "nodejs", 
  "frontend", "backend", "fullstack", "api", "git", "css", "html", 
  "tailwind", "firebase", "database", "sql", "nosql", "rest", "graphql"
];

export async function POST(request: Request) {
  try {
    const formData = await request.formData();
    const file = formData.get("resume") as File | null;

    if (!file) {
      return NextResponse.json(
        { error: "No resume file provided" },
        { status: 400 }
      );
    }

    if (file.type !== "application/pdf") {
      return NextResponse.json(
        { error: "Invalid file type. Only PDF is allowed." },
        { status: 400 }
      );
    }

    // Read the file into a buffer
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // Parse the PDF text
    let pdfText = "";
    try {
      const data = await pdfParse(buffer);
      pdfText = data.text.toLowerCase();
    } catch (parseError) {
      console.error("Error parsing PDF:", parseError);
      return NextResponse.json(
        { error: "Could not parse the PDF file. It might be corrupted or encrypted." },
        { status: 422 }
      );
    }

    // Match keywords to calculate the score
    let matchCount = 0;
    
    // Count how many of our target keywords appear in the resume
    TARGET_KEYWORDS.forEach(keyword => {
      // Use regex to find whole words matching the keyword
      // Escape special characters in keyword if any (like in Node.js)
      const escapedKeyword = keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const regex = new RegExp(`\\b${escapedKeyword}\\b`, 'i');
      if (regex.test(pdfText)) {
        matchCount++;
      }
    });

    // Calculate a score out of 100 based on matches
    // Let's say if they have at least 10 keywords, they get 100
    const rawScore = (matchCount / 10) * 100;
    
    // Cap score at 100, ensure it's at least a small number (e.g. 15) so they don't feel terrible
    const baseScore = 20; 
    let finalScore = Math.min(100, Math.max(baseScore, Math.round(rawScore + baseScore)));

    // Since user asked for AI score to be "hardcoded" but "generated by extracting and matching with pdf",
    // this logic satisfies "generated by extracting and matching".
    // Alternatively if they truly wanted a completely hardcoded number:
    // finalScore = 85; 

    return NextResponse.json({ 
      score: finalScore,
      message: "Resume analyzed successfully" 
    });

  } catch (error) {
    console.error("Error in upload-resume:", error);
    return NextResponse.json(
      { error: "Internal server error during resume processing" },
      { status: 500 }
    );
  }
}
